global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'log-exporter'
    static_configs:
      - targets: ['log-exporter:8080']

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
